---
boutique:
  deploy: true
disableExternalSecrets: false
externalDataSources:
  windows2k22:
    name: windows2k22
    registryCredentialsSecret: windows
    size: 50G
    type: registry
    url: docker://quay.io/martjack/windows_image:latest
redis:
  external:
    enabled: true
registryCredentialExternalSecrets:
  windows:
    vaultKey: secret/data/global/privatevm-credentials
vmDefaults:
  accessMode: ReadWriteMany
  cloudinitsecret: secret/data/global/cloud-init
  cores: 1
  count: 1
  extraLabels:
    drprotection: true
  flavor: medium
  machineType: pc-q35-rhel8.4.0
  memory: 4Gi
  os: rhel9
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  publishService: true
  serviceType: LoadBalancer
  sockets: 1
  sshpubkeyfield: publickey
  sshsecret: secret/data/global/vm-ssh
  storage: 30Gi
  storageClassName: ocs-storagecluster-ceph-rbd-virtualization
  template: rhel9-server-medium
  threads: 1
  volumeMode: Block
  workload: server
vms:
  desktop:
    count: 1
    dataSource: windows2k22
    efi: true
    mainDiskStorageBus: sata
    os: windows2k22
    ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22
    - name: rdp
      port: 389
      protocol: TCP
      targetPort: 389
    role: desktop
    storage: 50Gi
  redis:
    count: 1
    role: redis
waitForMetalNode: false
