---
agof:
  iac_repo: https://github.com/OAharoni-RedHat/ramendr-techdemo-config-as-code.git
  iac_revision: main
  # Use in-cluster hub Vault (doAutoHubVaultConfig); agof_vault.yml stays empty.
  vaultFileKey: ""
  doAutoHubVaultConfig: true
